/**
 * Canonical category list + SEO copy — single source of truth for the
 * real static per-category pages script/blog-builder.js generates
 * (category/<slug>/index.html). assets/js/category-ticker.js and
 * assets/js/category-seo.js carry their own copies of this same list for
 * the client-side ticker/legacy filtered page; keep all three in sync by
 * hand until they're unified into one shared JSON fetched by all three.
 *
 * theme = a mood-palette CSS class (see assets/css/style.css
 * .cat-theme-*) — gradients only, no photographic imagery.
 */
'use strict';

const CATEGORIES = [
  { slug: 'dark-romance', label: 'Dark Romance', emoji: '',
    title: 'Dark Romance Stories',
    description: 'Dark romance stories on mahmuda.fun: morally grey characters, high-stakes tension and intense emotional stakes. 18+ fiction.',
    intro: 'Dark romance leans into morally complicated characters and high tension — love that comes with real risk attached. Every story here is fiction, written for adult readers.',
    theme: 'danger' },
  { slug: 'mafia-romance', label: 'Mafia Romance', emoji: '🐴',
    title: 'Mafia Romance Stories',
    description: 'Mafia romance stories on mahmuda.fun: dangerous men, loyalty, and love that breaks every rule. 18+ fiction.',
    intro: 'Mafia romance pairs danger with devotion — power, loyalty, and a love interest who answers to no one but themselves.',
    theme: 'danger' },
  { slug: 'paranormal-fantasy-romance', label: 'Paranormal & Fantasy Romance', emoji: '🧙',
    title: 'Paranormal & Fantasy Romance Stories',
    description: 'Paranormal and fantasy romance stories on mahmuda.fun featuring otherworldly connections and impossible desire. 18+ fiction.',
    intro: 'Paranormal & fantasy romance steps outside the ordinary world entirely — supernatural pulls, fated connections, and desire that defies explanation.',
    theme: 'mystic' },
  { slug: 'billionaire-romance', label: 'Billionaire Romance', emoji: '💰',
    title: 'Billionaire Romance Stories',
    description: 'Billionaire romance stories on mahmuda.fun: wealth, power and the one thing money can’t buy. 18+ fiction.',
    intro: 'Billionaire romance is about the gap between what money can buy and what it can’t — and the tension that fills it.',
    theme: 'luxury' },
  { slug: 'alpha-males', label: 'Alpha Males', emoji: '💪',
    title: 'Alpha Male Romance Stories',
    description: 'Alpha male romance stories on mahmuda.fun: commanding, protective heroes and the readers who love them. 18+ fiction.',
    intro: 'Confident, commanding, protective — the alpha male archetype at the center of some of our most-read stories.',
    theme: 'luxury' },
  { slug: 'high-school-romance', label: 'High School Romance', emoji: '✏️',
    title: 'High School Romance Stories',
    description: 'High school romance stories on mahmuda.fun for adult readers (18+). All characters are written as adults.',
    intro: 'High school as a setting, written for adult readers — all characters depicted are adults. First crushes, rivalries and everything in between.',
    theme: 'warm' },
  { slug: 'spicy-romance', label: 'Spicy Romance', emoji: '🌶️',
    title: 'Spicy Romance Stories',
    description: 'Spicy romance stories on mahmuda.fun: heat-forward fiction for adult readers. 18+ only.',
    intro: 'For readers who want the temperature turned up — heat-forward romance fiction, 18+ only.',
    theme: 'rose' },
  { slug: 'age-gap-romance', label: 'Age Gap Romance', emoji: '👨‍🦳',
    title: 'Age Gap Romance Stories',
    description: 'Age gap romance stories on mahmuda.fun featuring a meaningful difference in life experience between leads. 18+ fiction — all characters are adults.',
    intro: 'Age gap romance explores connection across a real difference in life stage and experience. All characters depicted are adults.',
    theme: 'rose' },
  { slug: 'vampire-romance', label: 'Vampire Romance', emoji: '🧛',
    title: 'Vampire Romance Stories',
    description: 'Vampire romance stories on mahmuda.fun: immortal desire and gothic tension. 18+ fiction.',
    intro: 'Immortal, dangerous, magnetic — vampire romance brings a gothic edge to the usual rules of attraction.',
    theme: 'mystic' },
  { slug: 'cowboy-romance', label: 'Cowboy Romance', emoji: '🤠',
    title: 'Cowboy Romance Stories',
    description: 'Cowboy romance stories on mahmuda.fun: small-town charm and rugged heroes. 18+ fiction.',
    intro: 'Wide-open country, small-town charm, and heroes who work with their hands — cowboy romance at its most grounded.',
    theme: 'earthy' },
  { slug: 'forbidden-romance', label: 'Forbidden Romance', emoji: '💔',
    title: 'Forbidden Romance Stories',
    description: 'Forbidden romance stories on mahmuda.fun: love that isn’t supposed to happen. 18+ fiction.',
    intro: 'The oldest hook in romance for a reason — connection that crosses a line it shouldn’t, and can’t look away from.',
    theme: 'accent' },
  { slug: 'second-chance-romance', label: 'Second Chance Romance', emoji: '🔁',
    title: 'Second Chance Romance Stories',
    description: 'Second chance romance stories on mahmuda.fun: old love, new stakes. 18+ fiction.',
    intro: 'Second chance romance is about what’s left unfinished — old feelings resurfacing with everything now on the line.',
    theme: 'accent' },
  { slug: 'clean-wholesome', label: 'Clean & Wholesome', emoji: '✨',
    title: 'Clean & Wholesome Romance Stories',
    description: 'Clean and wholesome romance stories on mahmuda.fun: sweet, low-heat fiction for readers who want tension without explicit content.',
    intro: 'For readers who want the slow build and the swoon without the heat — clean and wholesome romance.',
    theme: 'warm' },
  { slug: 'fated-mates', label: 'Fated Mates', emoji: '💘',
    title: 'Fated Mates Romance Stories',
    description: 'Fated mates romance stories on mahmuda.fun: connections written in the stars. 18+ fiction.',
    intro: 'Some pairings feel inevitable from the first page — fated mates stories lean fully into that pull.',
    theme: 'mystic' },
  { slug: 'comedy', label: 'Comedy', emoji: '😂',
    title: 'Romantic Comedy Stories',
    description: 'Romantic comedy stories on mahmuda.fun: banter, chemistry and a lot of laughs. 18+ fiction.',
    intro: 'Romance doesn’t have to be all tension — these stories lead with banter, chemistry, and a sense of humor.',
    theme: 'warm' },
  { slug: 'bad-boys', label: 'Bad Boys', emoji: '🏍️',
    title: 'Bad Boy Romance Stories',
    description: 'Bad boy romance stories on mahmuda.fun: rule-breakers who make terrible decisions look good. 18+ fiction.',
    intro: 'The bad boy archetype, done right — rule-breakers with a soft spot they’ll never admit to.',
    theme: 'danger' },
  { slug: 'slow-burn', label: 'Slow Burn', emoji: '🔥',
    title: 'Slow Burn Romance Stories',
    description: 'Slow burn romance stories on mahmuda.fun: tension that builds patiently before it pays off. 18+ fiction.',
    intro: 'No instant sparks here — slow burn romance rewards patience with tension that builds page by page.',
    theme: 'accent' },
  { slug: 'enemies-to-lovers', label: 'Enemies to Lovers', emoji: '⚔️',
    title: 'Enemies to Lovers Romance Stories',
    description: 'Enemies to lovers romance stories on mahmuda.fun: rivalry that turns into something else entirely. 18+ fiction.',
    intro: 'They started as rivals. Enemies-to-lovers is the trope that turns that friction into something neither of them expected.',
    theme: 'danger' },
  { slug: 'sports', label: 'Sports', emoji: '🏈',
    title: 'Sports Romance Stories',
    description: 'Sports romance stories on mahmuda.fun: athletes, rivalry, and off-the-field chemistry. 18+ fiction.',
    intro: 'Competition, discipline, and the chemistry that happens once the game is over — sports romance.',
    theme: 'earthy' },
  { slug: 'college', label: 'College', emoji: '🎓',
    title: 'College Romance Stories',
    description: 'College romance stories on mahmuda.fun for adult readers (18+). All characters are written as adults.',
    intro: 'The freedom, chaos and firsts of college life, written for adult readers — all characters depicted are adults.',
    theme: 'warm' },
  // Added on request to match the site's actual most-used tags (relationship
  // tropes, not explicit act descriptors — kept to that same line as the
  // rest of this list; see the PR notes for what was deliberately left out).
  { slug: 'bhabi-romance', label: 'Bhabi Romance', emoji: '💍',
    title: 'Bhabi Romance Stories',
    description: 'Bhabi romance stories on mahmuda.fun: forbidden closeness within the family, tension and desire. 18+ fiction — all characters are adults.',
    intro: 'A recurring trope in South Asian romance fiction — closeness inside the family that turns into something forbidden. All characters depicted are adults.',
    theme: 'accent', image: 'assets/images/categories/Bhabi-saree.jpg' },
  { slug: 'affair-romance', label: 'Affair & Cheating Romance', emoji: '💋',
    title: 'Affair & Cheating Romance Stories',
    description: 'Affair and cheating-wife romance stories on mahmuda.fun: infidelity, guilt and desire that won’t stay hidden. 18+ fiction.',
    intro: 'Affair fiction leans into what happens when desire crosses a line that was never meant to be crossed.',
    theme: 'rose' },
];

module.exports = { CATEGORIES };
